export const data = [
  {
    id: 'KriBQVhsgZk',
    name: 'Nike Football: The Last Game full edition',
    url: 'https://www.youtube.com/watch?v=KriBQVhsgZk',
    channel: 'mycoolvideos',
    subscribers: '608K subscribers',
    channelThumbnail: 'https://yt3.ggpht.com/ytc/AAUvwnjfYMhXA4RvzNqAdmou4FWZ2H6hMVhbY0YcAFf5=s176-c-k-c0x00ffffff-no-rj',
    videoThumbnail: 'http://img.youtube.com/vi/KriBQVhsgZk/hqdefault.jpg',
    videoDescription: 'Nike Football: The Last Game full edition',
    views: '156,843,318',
    time: '7:02',
  },
  {
    id: 'AUyOZAfnehM',
    name: '10 MOST FUNNY PENALTY KICKS IN FOOTBALL',
    url: 'https://www.youtube.com/watch?v=AUyOZAfnehM',
    channel: 'Trend Wave',
    subscribers: '1.7M subscribers',
    channelThumbnail: 'https://yt3.ggpht.com/ytc/AAUvwnjJeM2TDHCGdxUfUGMLKComSwhuMFSd7Ogj6XwB=s176-c-k-c0x00ffffff-no-rj',
    videoThumbnail: 'http://img.youtube.com/vi/AUyOZAfnehM/maxresdefault.jpg',
    videoDescription: '10 MOST FUNNY PENALTY KICKS IN FOOTBALL',
    views: '80,124,556',
    time: '3:04',
  },
  {
    id: 'cqylLiMzk54',
    name: 'Freeze Frame Football Battle | Dude Perfect',
    url: 'https://www.youtube.com/watch?v=cqylLiMzk54',
    channel: 'Dude Perfect',
    subscribers: '55.8M subscribers',
    channelThumbnail: 'https://yt3.ggpht.com/ytc/AAUvwni8alaul0s34_VP1Vgo9zQvdvXPacigPR_40AgdpA=s176-c-k-c0x00ffffff-no-rj',
    videoThumbnail: 'http://img.youtube.com/vi/cqylLiMzk54/maxresdefault.jpg',
    videoDescription: 'Freeze Frame Football Battle | Dude Perfect',
    views: '95,893,426',
    time: '6:52',
  },
  {
    id: '1B_7JxGsK7Y',
    name: 'Top 10 Best Corner Kick Goals In Football',
    url: 'https://www.youtube.com/watch?v=1B_7JxGsK7Y',
    channel: 'Wrzzer',
    subscribers: '4.01M subscribers',
    channelThumbnail: 'https://yt3.ggpht.com/ytc/AAUvwnhMZ7oyDluTd9RRz_SKCLvaIGzQW8Npt8Q3yVE4=s176-c-k-c0x00ffffff-no-rj',
    videoThumbnail: 'http://img.youtube.com/vi/1B_7JxGsK7Y/maxresdefault.jpg',
    videoDescription: 'Top 10 Best Corner Kick Goals In Football',
    views: '94,372,989',
    time: '3:41',
  },
];
