export const data = [
  {
    id: 'KriBQVhsgZk',
    name: 'Nike Football: The Last Game full edition',
    url: 'https://www.youtube.com/watch?v=KriBQVhsgZk',
    channel: 'mycoolvideos',
    thumbnail: 'http://img.youtube.com/vi/KriBQVhsgZk/hqdefault.jpg',
    viewes: '156,843,318',
    time: '7:02',
  },
  {
    id: 'AUyOZAfnehM',
    name: '10 MOST FUNNY PENALTY KICKS IN FOOTBALL',
    url: 'https://www.youtube.com/watch?v=AUyOZAfnehM',
    channel: 'Trend Wave',
    thumbnail: 'http://img.youtube.com/vi/AUyOZAfnehM/hqdefault.jpg',
    viewes: '80,124,556',
    time: '3:04',
  },
  {
    id: 'cqylLiMzk54',
    name: 'Freeze Frame Football Battle | Dude Perfect',
    url: 'https://www.youtube.com/watch?v=cqylLiMzk54',
    channel: 'Dude Perfect',
    thumbnail: 'http://img.youtube.com/vi/cqylLiMzk54/hqdefault.jpg',
    viewes: '95,893,426',
    time: '6:52',
  },
  {
    id: '1B_7JxGsK7Y',
    name: 'Top 10 Best Corner Kick Goals In Football',
    url: 'https://www.youtube.com/watch?v=1B_7JxGsK7Y',
    channel: 'Wrzzer',
    thumbnail: 'http://img.youtube.com/vi/1B_7JxGsK7Y/hqdefault.jpg',
    viewes: '94,372,989',
    time: '3:41',
  },
];
