export const data = [
  {
    id: 'KriBQVhsgZk',
    name: 'Nike Football: The Last Game full edition',
    url: 'https://www.youtube.com/watch?v=KriBQVhsgZk',
    channel: 'mycoolvideos',
    subscribers: '608K subscribers',
    channelThumbnail: 'https://yt3.ggpht.com/ytc/AAUvwnjfYMhXA4RvzNqAdmou4FWZ2H6hMVhbY0YcAFf5=s176-c-k-c0x00ffffff-no-rj',
    videoThumbnail: 'http://img.youtube.com/vi/KriBQVhsgZk/hqdefault.jpg',
    videoDescription: 'Nike Football: The Last Game full edition',
    views: '156,843,318',
    time: '7:02',
  },
  {
    id: 'AUyOZAfnehM',
    name: '10 MOST FUNNY PENALTY KICKS IN FOOTBALL',
    url: 'https://www.youtube.com/watch?v=AUyOZAfnehM',
    channel: 'Trend Wave',
    subscribers: '1.7M subscribers',
    channelThumbnail: 'https://yt3.ggpht.com/ytc/AAUvwnjJeM2TDHCGdxUfUGMLKComSwhuMFSd7Ogj6XwB=s176-c-k-c0x00ffffff-no-rj',
    videoThumbnail: 'http://img.youtube.com/vi/AUyOZAfnehM/hqdefault.jpg',
    videoDescription: '10 MOST FUNNY PENALTY KICKS IN FOOTBALL',
    views: '80,124,556',
    time: '3:04',
  },
  {
    id: 'cqylLiMzk54',
    name: 'Freeze Frame Football Battle | Dude Perfect',
    url: 'https://www.youtube.com/watch?v=cqylLiMzk54',
    channel: 'Dude Perfect',
    subscribers: '55.8M subscribers',
    channelThumbnail: 'https://yt3.ggpht.com/ytc/AAUvwni8alaul0s34_VP1Vgo9zQvdvXPacigPR_40AgdpA=s176-c-k-c0x00ffffff-no-rj',
    videoThumbnail: 'http://img.youtube.com/vi/cqylLiMzk54/hqdefault.jpg',
    videoDescription: 'Freeze Frame Football Battle | Dude Perfect',
    views: '95,893,426',
    time: '6:52',
  },
  {
    id: '1B_7JxGsK7Y',
    name: 'Top 10 Best Corner Kick Goals In Football',
    url: 'https://www.youtube.com/watch?v=1B_7JxGsK7Y',
    channel: 'Wrzzer',
    subscribers: '4.01M subscribers',
    channelThumbnail: 'https://yt3.ggpht.com/ytc/AAUvwnhMZ7oyDluTd9RRz_SKCLvaIGzQW8Npt8Q3yVE4=s176-c-k-c0x00ffffff-no-rj',
    videoThumbnail: 'http://img.youtube.com/vi/1B_7JxGsK7Y/hqdefault.jpg',
    videoDescription: 'Top 10 Best Corner Kick Goals In Football',
    views: '94,372,989',
    time: '3:41',
  },
  {
    id: '0dlGsFUMxJs',
    name: 'Unstoppable Plays in Football 2021',
    url: 'https://www.youtube.com/watch?v=0dlGsFUMxJs',
    channel: 'Teo CRi',
    subscribers: '2.4M subscribers',
    channelThumbnail: 'https://yt3.ggpht.com/ytc/AAUvwng-OY8q-r7h0zLK3Rx-wExZPfr4uhuUU1-EcMUVlQ=s88-c-k-c0x00ffffff-no-rj',
    videoThumbnail: 'http://img.youtube.com/vi/0dlGsFUMxJs/hqdefault.jpg',
    videoDescription: 'Unstoppable skills, goals, speed in football 2020/21. Oustanding moments, featuring some of the best players in the world, such as Mbappe, Haland, Cristiano Ronaldo, Messi, Neymar, Bruno Fernandes and much, muuuuuch more!',
    views: '8,100',
    time: '10:12',
  },
  {
    id: 'qh-yxk-qAOc',
    name: 'Unforgettable Goals in Football #2',
    url: 'https://www.youtube.com/watch?v=qh-yxk-qAOc',
    channel: 'TKHD',
    subscribers: '2.73M subscribers',
    channelThumbnail: 'https://yt3.ggpht.com/ytc/AAUvwni9Kb70j90xSwFzQtbjlq4vR4ZC0HB61Wd71sIDiA=s88-c-k-c0x00ffffff-no-rj',
    videoThumbnail: 'http://img.youtube.com/vi/qh-yxk-qAOc/hqdefault.jpg',
    videoDescription: 'Unforgettable and best goals in football. Messi, Ronaldo, Ibrahimovic, Rashford and more in the video!',
    views: '12,848,865',
    time: '9:47',
  },
  {
    id: 'qZHycHI3F1Q',
    name: 'Football vs Soccer Trick Shots | Dude Perfect',
    url: 'https://www.youtube.com/watch?v=qZHycHI3F1Q',
    channel: 'Dude Perfect',
    subscribers: '56.1M subscribers',
    channelThumbnail: 'https://yt3.ggpht.com/ytc/AAUvwni8alaul0s34_VP1Vgo9zQvdvXPacigPR_40AgdpA=s88-c-k-c0x00ffffff-no-rj',
    videoThumbnail: 'http://img.youtube.com/vi/qZHycHI3F1Q/hqdefault.jpg',
    videoDescription: 'Dude Perfect football vs F2 soccer... trick shot style! ',
    views: '93,977,699',
    time: '6:38',
  },
  {
    id: '_dBz4dTZocg',
    name: 'Ronaldinho - Football Greatest Entertainment',
    url: 'https://www.youtube.com/watch?v=_dBz4dTZocg',
    channel: 'JavierNathaniel',
    subscribers: '1.9M subscribers',
    channelThumbnail: 'https://yt3.ggpht.com/ytc/AAUvwnhbd_UBlf9QchU-g4cydcAJZ8H_Iw3yBuPdoJ_u=s88-c-k-c0x00ffffff-no-rj',
    videoThumbnail: 'http://img.youtube.com/vi/_dBz4dTZocg/hqdefault.jpg',
    videoDescription: 'Ronaldinho Gaúcho best skills & goals for FC Barcelona, Brazil, AC Milan. PSG & more!',
    views: '45,515,086',
    time: '13:26',
  },
  {
    id: 'RchmNRQ_r70',
    name: 'Creative Skills in Football',
    url: 'https://www.youtube.com/watch?v=RchmNRQ_r70',
    channel: 'iFutGol',
    subscribers: '3.28M subscribers',
    channelThumbnail: 'https://yt3.ggpht.com/ytc/AAUvwngpkyWGFafK6SefeNhToLy7UfkJLs2Zg4QdWSP29Q=s88-c-k-c0x00ffffff-no-rj',
    videoThumbnail: 'http://img.youtube.com/vi/RchmNRQ_r70/hqdefault.jpg',
    videoDescription: 'Creative Skills in Football ',
    views: '42,521,848',
    time: '7:32',
  },
  {
    id: 'Ny2S4YURXBA',
    name: 'Impossible Saves',
    url: 'https://www.youtube.com/watch?v=Ny2S4YURXBA',
    channel: 'SportsHD',
    subscribers: '4.26M subscribers',
    channelThumbnail: 'https://yt3.ggpht.com/ytc/AAUvwng_7qPG-x8aocG3UKUmbx_BvzLqXw6Mx3CNK921kA=s88-c-k-c0x00ffffff-no-rj',
    videoThumbnail: 'http://img.youtube.com/vi/Ny2S4YURXBA/hqdefault.jpg',
    videoDescription: 'Impossible Saves',
    views: '35,900,641',
    time: '6:00',
  },
];
